version: '3.8'

services:
  api:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: news-classifier-api
    ports:
      - "8000:8000"
    volumes:
      - ./models:/app/models

  streamlit:
    build:
      context: .
      dockerfile: Dockerfile.streamlit
    container_name: news-classifier-streamlit
    ports:
      - "8501:8501"
    depends_on:
      - api
    environment:
      - API_URL=http://api:8000